#!/usr/bin/env python3
"""
Environment Setup Script for Tanzania Service Chatbot
Helps users configure their WhatsApp credentials and environment
"""

import os
import sys
from pathlib import Path

def setup_environment():
    """Interactive environment setup"""
    print("🇹🇿 Tanzania Service Chatbot - Environment Setup")
    print("=" * 55)
    print()

    # Check if .env already exists
    env_file = Path('.env')
    if env_file.exists():
        response = input("⚠️  .env file already exists. Overwrite? (y/N): ").lower().strip()
        if response != 'y':
            print("Setup cancelled.")
            return

    print("Choose your WhatsApp provider:")
    print("1. Meta WhatsApp Business API (Global)")
    print("2. Ghala WhatsApp API (Tanzania-focused) - Recommended")
    print()

    while True:
        choice = input("Enter choice (1 or 2): ").strip()
        if choice == '1':
            provider = 'meta'
            break
        elif choice == '2':
            provider = 'ghala'
            break
        else:
            print("Please enter 1 or 2.")

    print(f"\n✅ Selected: {provider.upper()} WhatsApp API")
    print()

    # Collect credentials based on provider
    env_vars = {}

    if provider == 'meta':
        print("📋 Meta WhatsApp Business API Credentials:")
        print("   Get these from: https://developers.facebook.com/")
        print()

        env_vars['WHATSAPP_ACCESS_TOKEN'] = input("WhatsApp Access Token: ").strip()
        env_vars['WHATSAPP_PHONE_NUMBER_ID'] = input("WhatsApp Phone Number ID: ").strip()
        env_vars['WHATSAPP_WABA_ID'] = input("WhatsApp Business Account ID (WABA ID): ").strip()
        env_vars['WHATSAPP_WEBHOOK_TOKEN'] = input("Webhook Verify Token (default: tanzania_service_bot_2024): ").strip() or 'tanzania_service_bot_2024'

    elif provider == 'ghala':
        print("📋 Ghala WhatsApp API Credentials:")
        print("   Get these from: https://dev.ghala.io/")
        print()

        env_vars['GHALA_APP_ID'] = input("Ghala App ID: ").strip()
        env_vars['GHALA_APP_SECRET'] = input("Ghala App Secret: ").strip()
        env_vars['GHALA_WEBHOOK_TOKEN'] = input("Webhook Verify Token (default: tanzania_service_bot_ghala): ").strip() or 'tanzania_service_bot_ghala'

    # Server configuration
    print("\n⚙️  Server Configuration:")
    host = input("Host (default: 0.0.0.0): ").strip() or '0.0.0.0'
    port = input("Port (default: 5000): ").strip() or '5000'
    debug = input("Debug mode (default: false): ").strip().lower()
    debug = 'true' if debug in ['true', 'yes', 'y'] else 'false'

    env_vars.update({
        'WHATSAPP_PROVIDER': provider,
        'HOST': host,
        'PORT': port,
        'DEBUG': debug
    })

    # Optional OSM API key
    osm_key = input("\n🔧 Optional - OpenStreetMap API Key (leave empty to skip): ").strip()
    if osm_key:
        env_vars['OSM_API_KEY'] = osm_key

    # Create .env file
    print("\n📄 Creating .env file...")
    try:
        with open('.env', 'w') as f:
            f.write("# Tanzania Service Chatbot Environment Configuration\n")
            f.write("# Auto-generated by setup_environment.py\n")
            f.write("\n")
            for key, value in env_vars.items():
                f.write(f"{key}={value}\n")

        print("✅ .env file created successfully!")
        print("📍 Location: .env")
        print()

        # Test configuration
        print("🧪 Testing configuration...")
        from env_config import Config

        if Config.is_whatsapp_configured():
            print("✅ WhatsApp configuration is valid!")
        else:
            print("❌ WhatsApp configuration is incomplete.")
            print("   Please check your credentials and try again.")

        print()
        print("🚀 Next steps:")
        print("1. Test your setup: python main.py --whatsapp")
        print("2. For production: Set up webhook URL in your WhatsApp dashboard")
        print("3. Run the bot: ./run_whatsapp.sh")

    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        print("   You can manually create the file with the following content:")
        print()
        for key, value in env_vars.items():
            print(f"   {key}={value}")

def main():
    """Main function"""
    if len(sys.argv) > 1 and sys.argv[1] == '--help':
        print("Environment Setup for Tanzania Service Chatbot")
        print()
        print("This script helps you configure your WhatsApp credentials")
        print("and create the necessary environment variables.")
        print()
        print("Usage:")
        print("  python setup_environment.py    # Interactive setup")
        print("  python setup_environment.py --help    # Show this help")
        return

    setup_environment()

if __name__ == "__main__":
    main()
